### PR TITLE
fix: Create output with full range

### PR DESCRIPTION
**Pull request by polarathene**
Hi, thanks for sharing the code and youtube video. It was helpful to visualize and understand spherical harmonics! :smiley:

I noticed that there was always a gap / opening in the visualization for some reason. As I gained a better understanding of the code I noticed you're culling/truncating the first and last rows/columns of data at the for loop ranges. Any reason for that?

They end up being 0 placing them in the origin which results in a faulty construction of the mesh/result. I fixed this by using the full range, and then noticed some errors output in the console regarding division by zero. Matplotlib then graphed the result but without the gradient colour fill. 

I replaced the method to calculate Legendre Polynomials from another project and it resolved the issue, you might know how to better fix the original methods instead if you prefer?

See the indvidual commit messages for more details :)

### CODE REVIEW

**Comment by polarathene** [comment]
@PyPhy I see you've been adding new commits to the repo, but no activity on this PR. Were you not aware of it? (I know sometimes I don't get notifications of activity on my own projects)

**Comment by PyPhy** [comment]
Hello,

Sorry for the late reply. I have seen your previous email and I really
appreciate it.

But during this period, I was busy in my college exam (yes, in lockdown).
In addition to that, GitHub is new to me. I only how to upload a code on it
but I'm not aware of any other features. That is the reason why I haven't
responded.

Once again, I'm really sorry about that. You can tell me what steps should
I follow to accept the request on GitHub.

Thank you.

**Comment by polarathene** [comment]
@PyPhy no problem! :smile: 

This is a pull request. It is how others can contribute improvements or new features to a project.

If you're familiar with `git`, there is cloning/forking of a repository project like your one here. I made a copy of yours, then added some changes. At the top below the title, you can see some options, in english there is "Files Changed" as one of those, if you click that, it will show you the changes I have made. What you see is called a "diff", the red is lines that have been modified or deleted, green is changes or new code added.

If you like those changes and would like to add them to your project here. There should be some buttons at the bottom of this page to to "Merge"/approve the pull request. All this does is accept them, and you will notice a new commit on your project history. 

Github documents the feature in detail [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

**Comment by polarathene** [comment]
I forgot to mention, I am communicating with you via the Github website. I just realized you may only be using email and the Github app or command line to update your projects.

You can find this page by visiting your repo on Github and viewing your pull requests tab. This is the page for this PR: https://github.com/PyPhy/Python/pull/1

**Comment by PyPhy** [comment]
Hello, 😄

I have followed the steps that you have suggested and Merged the request.

**Comment by polarathene** [comment]
Fantastic, thanks! :)

**Pull request merged**
